Finished gulpfile, added connect server & live reload

diff --git a/buildme b/buildme
--- a/buildme
+++ b/buildme
@@ -1,5 +1,5 @@
 #!/bin/bash
-set -e #Exit with error code on error.
+set -e # Exit with error code on error.
 
 echo "Installing node modules..."
 npm install
@@ -12,6 +12,5 @@ echo "...done"
 echo "Running gulp build step..."
 gulp
 echo "...done"
-
 
 echo "Finished building soundnex.us!"
